service: saparus

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: saparus-products
      localDir: client/build
# Backend: Lambda + API Gateway configuration
functions:
  # products
  addProduct:
    handler: products.addProduct
    events:
      - http:
          path: products
          method: post

  getCategories:
    handler: products.getCategories
    events:
      - http:
          path: products/categories
          method: get

  getProduct:
    handler: products.getProduct
    events:
      - http:
          path: products/{id}
          method: get

  getProducts:
    handler: products.getProducts
    events:
      - http:
          path: products
          method: get

  editProduct:
    handler: products.editProduct
    events:
      - http:
          path: products/{id}
          method: put

  deleteProduct:
    handler: products.deleteProduct
    events:
      - http:
          path: products/{id}
          method: delete

  # authentication
  register:
    handler: auth.register
    events:
      - http:
          path: auth/register
          method: post

  login:
    handler: auth.login
    events:
      - http:
          path: auth/login
          method: post

resources:
  Resources:
    # CloudFront distribution for serving the frontend
    FrontendCloudFront:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: 'true'
          Origins:
            - DomainName: saparus-products.s3.us-west-2.amazonaws.com
              Id: S3Origin
              S3OriginConfig:
                OriginAccessIdentity: ''
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: 'none'
          DefaultRootObject: index.html

# Define the deployment path for frontend files
package:
  exclude:
    - "server/**"
  include:
    - "client/**"

